name: 'Plouf!'
favicon: null
layout_spectrum: 0.5649306466802955
typography_spectrum: 0.8392626733984798
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8087090000044554
  lightness: 0.10200917371548712
  saturation: 0.3727350062690675
  rhythmicContrast: 0.28578907856717706
purpose: []
