name: 'Plouf!'
favicon: null
layout_spectrum: 0.49726
typography_spectrum: 0.48695
title: 'Plouf!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010302'
    - '#01394a'
    - '#bdc0ab'
    - '#e7f0ed'
    - '#037f87'
  brandStrength: 0.8087090000044554
  lightness: 0.10200917371548712
  saturation: 0.3727350062690675
  rhythmicContrast: 0.28578907856717706
purpose: []
