name: 'Plouf!'
favicon: null
layout_spectrum: 0.49726
typography_spectrum: 0.48695
title: 'Plouf!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16273b'
    - '#3d6a4d'
    - '#7c9a5a'
    - '#c9c56c'
    - '#897f42'
  brandStrength: 0.8087090000044554
  lightness: 0.10200917371548712
  saturation: 0.3727350062690675
  rhythmicContrast: 0.28578907856717706
purpose: []
